name: gesturegame master
 
on:
  push:
    branches:
      - master
 
jobs:
  deploy:
 
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v2
      
      - name: setup
        run: cd demos && yarn
      
      - name: build
        run: yarn watch

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
